TEXT_LIST = ["Please specify a name", "Invalid character", "Name already exists", "Invalid character for description",
             "Please specify a unit", "Unrecognized unit", "Please specify upper bound", "Bounds must be numbers",
             "Bounds must be strictly positive", "Lower bound must be strictly inferior to upper bound", "Output",
             "Check pi set", "Output parameters are found in multiple pi numbers", "Pi set valid",
             "Modify pi set", "Invalid pi set: ", "Saved", "Save", "The given pi set is valid", "Loaded", "Load",
             "No expression specified", "Name", "Description", "Unit", "Add parameter", 'Delete parameter',
             'Toggle Input / Output', "No parameter added", "Cannot set constant as output",
             "For constants, do not specify a lower bound",
             "Higher parameters have higher priority to be repetitive parameters ",
             "No physical parameter defined, please define physical parameters in the previous tab",
             "Physical parameters changed", 'Buckingham theorem output',
             "The equation variables must have the same name as in the previous tab", "Declare pi number",
             "Add pi number", 'Copy selected pi set', "Forced Pi numbers", "Automatic Buckingham", 'Pi set number',
             'Expressions', "No pi set generated", "Choose this Pi set", "Simple Buckingham", "Manual Buckingham",
             "Automatic Buckingham", "No pi set selected", "Pi set kept for DOE:", "Output pi removed from DOE:",
             "Invalid name", "Selected pi set:", "No pi set selected"]
